### ISSUE TITLE
./manage.py loaddata sites fails on macOS

### ISSUE THREAD

**Issue by moonchen** [ARMmbed/ref-wem-webapp#16]
```
(ref-wem-webapp) moche01@C02T301TGTFM:~/work/ref-wem-webapp$ ./manage.py loaddata sites
Traceback (most recent call last):
  File "./manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/moche01/OneDrive - ARM/work/ref-wem-webapp/wem/urls.py", line 26, in <module>
    url(r"^live-device/", include("livedevice.urls")),
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/moche01/OneDrive - ARM/work/ref-wem-webapp/livedevice/urls.py", line 21, in <module>
    from livedevice.views import (
  File "/Users/moche01/OneDrive - ARM/work/ref-wem-webapp/livedevice/views.py", line 38, in <module>
    from .cloud_data_handlers import handle_data
  File "/Users/moche01/OneDrive - ARM/work/ref-wem-webapp/livedevice/cloud_data_handlers.py", line 29, in <module>
    '/26242/0/1': Channel('gis.locate').send
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/channels/channel.py", line 30, in __init__
    self.channel_layer = channel_layers[alias]
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/channels/asgi.py", line 70, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/channels/asgi.py", line 33, in make_backend
    return self._make_backend(name, config)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/channels/asgi.py", line 61, in _make_backend
    asgi_layer = backend_class(**config)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/asgi_ipc/core.py", line 39, in __init__
    self.message_store = ChannelMemoryStore("%s-messages" % prefix, message_memory)
  File "/Users/moche01/.virtualenvs/ref-wem-webapp/lib/python2.7/site-packages/asgi_ipc/store.py", line 29, in __init__
    self.memory = posix_ipc.SharedMemory(path, flags=posix_ipc.O_CREAT, size=self.memory_size)
ValueError: The size is invalid or the memory is read-only
```

**Comment by mbanders** [comment]
Added a note saying we support linux: https://github.com/ARMmbed/ref-wem-webapp/commit/3e9956564f73c2a5cfb61028b84edaa34acec75a

Not working on supporting other OS at this time.
